from models.base import Base
from models.hotel import Hamburgueria
from models.cliente import Cliente
from .funcionario import Funcionario
from .pedido import Pedido
from .produto import Produto
from .cardapio import Cardapio
from .pagamento import Pagamento
from .forma_pagamento import FormaPagamento
from .pedido_tem_produto import PedidoTemProduto
from .cliente_pedido import ClientePedido
from .categoria_produto import CategoriaProduto
from .promocao import Promocao
from .historico_pedido import HistoricoPedido
from .funcao_funcionario import FuncaoFuncionario
from .feedback_cliente import FeedbackCliente
from .fornecedor import Fornecedor
from .estoque_produto import EstoqueProduto
from .pagamento_salario_funcionario import PagamentoSalarioFuncionario
